### ISSUE TITLE
Deprecation warning for SUBDIRS variable in linux kernel module build

### ISSUE THREAD

**Issue by wilhelmy** [OpenCBM/OpenCBM#23] opened 2019-11-09 16:24 UTC
```
make -C /lib/modules/5.3.7-1-default/build here=`pwd` OPENCBM_KERNEL_FLAGS="" SUBDIRS=`pwd` modules
make[2]: Entering directory '/usr/src/linux-5.3.7-1-obj/x86_64/default'
/usr/src/linux-5.3.7-1/Makefile:213: ================= WARNING ================
/usr/src/linux-5.3.7-1/Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
/usr/src/linux-5.3.7-1/Makefile:215: 
/usr/src/linux-5.3.7-1/Makefile:216: If you are building an individual subdirectory
/usr/src/linux-5.3.7-1/Makefile:217: in the kernel tree, you can do like this:
/usr/src/linux-5.3.7-1/Makefile:218: $ make path/to/dir/you/want/to/build/
/usr/src/linux-5.3.7-1/Makefile:219: (Do not forget the trailing slash)
/usr/src/linux-5.3.7-1/Makefile:220: 
/usr/src/linux-5.3.7-1/Makefile:221: If you are building an external module,
/usr/src/linux-5.3.7-1/Makefile:222: Please use 'M=' or 'KBUILD_EXTMOD' instead
/usr/src/linux-5.3.7-1/Makefile:223: ==========================================
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory '/usr/src/linux-5.3.7-1-obj/x86_64/default'
```

**Comment by spiro-trikaliotis** [comment] 2019-12-21 14:23
Thank you for your report. The issue is fixed in commit 4b1afe53.

**Closed** 2019-12-21 14:22 UTC
